//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Matriz_Riesgo_Politica
{
    using System;
    using System.Collections.Generic;
    
    public partial class accionRiesgo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public accionRiesgo()
        {
            this.detalleAnalisisRiesgoes = new HashSet<detalleAnalisisRiesgo>();
        }
    
        public int codigoAccion { get; set; }
        public int codigoPosibilidad { get; set; }
        public int codigoImpacto { get; set; }
        public string descripcionAccion { get; set; }
    
        public virtual impactoRiesgo impactoRiesgo { get; set; }
        public virtual posibilidadRiesgo posibilidadRiesgo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalleAnalisisRiesgo> detalleAnalisisRiesgoes { get; set; }
    }
}
