//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Matriz_Riesgo_Politica
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Activo()
        {
            this.cabeceraAnalisisRiesgoes = new HashSet<cabeceraAnalisisRiesgo>();
        }
    
        public int codigoActivo { get; set; }
        public string nombreActivo { get; set; }
        public Nullable<decimal> costoActivo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cabeceraAnalisisRiesgo> cabeceraAnalisisRiesgoes { get; set; }
    }
}
