//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Matriz_Riesgo_Politica
{
    using System;
    using System.Collections.Generic;
    
    public partial class cabeceraAnalisisRiesgo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cabeceraAnalisisRiesgo()
        {
            this.detalleAnalisisRiesgoes = new HashSet<detalleAnalisisRiesgo>();
        }
    
        public int codigoAnalisisRiesgo { get; set; }
        public Nullable<System.DateTime> fechaCreacion { get; set; }
        public string nombreAuditor { get; set; }
        public string nombreAprobador { get; set; }
        public string nivelConfidencialidad { get; set; }
        public Nullable<int> codigoActivo { get; set; }
        public string objetivosAnalisisRiesgo { get; set; }
        public string alcanceAnalisisRiesgo { get; set; }
    
        public virtual Activo Activo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalleAnalisisRiesgo> detalleAnalisisRiesgoes { get; set; }
    }
}
