//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Matriz_Riesgo_Politica
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalleAnalisisRiesgo
    {
        public int codigoDetalleRiesgo { get; set; }
        public int codigoAnalisisRiesgo { get; set; }
        public Nullable<int> codigoCategoriaAmenza { get; set; }
        public Nullable<int> codigoImpacto { get; set; }
        public Nullable<int> codigoPosibilidad { get; set; }
        public string nombreRiesgo { get; set; }
        public Nullable<int> codigoAccionRiesgo { get; set; }
    
        public virtual cabeceraAnalisisRiesgo cabeceraAnalisisRiesgo { get; set; }
        public virtual categoriasAmenaza categoriasAmenaza { get; set; }
        public virtual configuracionRiesgo configuracionRiesgo { get; set; }
        public virtual impactoRiesgo impactoRiesgo { get; set; }
        public virtual posibilidadRiesgo posibilidadRiesgo { get; set; }
    }
}
