//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Matriz_Riesgo_Politica
{
    using System;
    using System.Collections.Generic;
    
    public partial class seccionPoliticaAmenaza
    {
        public int codigoSeccionPolitica { get; set; }
        public Nullable<int> codigoEnunciadoPolitica { get; set; }
        public string descripcionSeccion { get; set; }
    
        public virtual enunciadoPoliticaAmenaza enunciadoPoliticaAmenaza { get; set; }
    }
}
